### ISSUE TITLE
sfdisk -uM not supported anymore

### ISSUE THREAD

**Issue by r1k0** [r1k0/kicktoo#14]
``` bash
root ~/kicktoo # ./kicktoo -p  profiles/gentoo/gentoo.profile  -d -v
import(): imported module output from /root/kicktoo/modules
import(): imported module misc from /root/kicktoo/modules
import(): imported module spawn from /root/kicktoo/modules
import(): imported module fetcher from /root/kicktoo/modules
bootloader.sh(): loading arch-specific module bootloader_amd64.sh
import(): imported module bootloader_x86 from /root/kicktoo/modules
import(): imported module bootloader_amd64 from /root/kicktoo/modules
import(): imported module bootloader from /root/kicktoo/modules
partition.sh(): loading arch-specific module partition_amd64.sh
import(): imported module partition_x86 from /root/kicktoo/modules
import(): imported module partition_amd64 from /root/kicktoo/modules
import(): imported module partition from /root/kicktoo/modules
import(): imported module runsteps from /root/kicktoo/modules
import(): imported module profile from /root/kicktoo/modules
import(): imported module stepcontrol from /root/kicktoo/modules
import(): imported module server from /root/kicktoo/modules
spawn(): running command 'mkdir -p /tmp/.kicktoo-autoresume'
main(): profile_name is: 'gentoo'
part(): partitions_sdb is now: 1:83:100M:
part(): partitions_sdb is now: 1:83:100M: 2:82:2048M:
part(): partitions_sdb is now: 1:83:100M: 2:82:2048M: 3:83:+:
stage_latest(): latest stage uri is http://distfiles.gentoo.org/releases/amd64/autobuilds/20150416/stage3-amd64-20150416.tar.bz2
spawn(): running command 'mkdir -p /tmp/.kicktoo-autoresume/gentoo'
 >>> Cleaning up system environment
runstep(): executing main for starting_cleanup
main(): Pushing system for amd64
 >>> Running pre-install script if any
runstep(): executing main for run_pre_install_script
run_pre_install_script(): no pre-install script set
 >>> Partitioning
runstep(): executing main for partition
partition(): device is sdb
create_disklabel(): creating new msdos disklabel
spawn(): running command 'parted /dev/sdb --script -- mklabel msdos'
partition(): partition is 1:83:100M:
partition(): devnode is /dev/sdb1
human_size_to_mb(): size=100M, device_size=476938
human_size_to_mb(): number_suffix='100|M', number=100, suffix=M
human_size_to_mb(): size=100, device_size=476838
part(): partitions are now: ,100,83,
partition(): partition is 2:82:2048M:
partition(): devnode is /dev/sdb2
human_size_to_mb(): size=2048M, device_size=476838
human_size_to_mb(): number_suffix='2048|M', number=2048, suffix=M
human_size_to_mb(): size=2048, device_size=474790
part(): partitions are now: ,100,83,\n,2048,82,
partition(): partition is 3:83:+:
partition(): devnode is /dev/sdb3
human_size_to_mb(): size=+, device_size=474790
human_size_to_mb(): size is + or blank...using rest of drive
human_size_to_mb(): size=, device_size=0
part(): partitions are now: ,100,83,\n,2048,82,\n,,83,
sfdisk_command(): running sfdisk partitions ',100,83,\n,2048,82,\n,,83,' on device /dev/sdb with geometry 
spawn(): running command 'echo -e ',100,83,\n,2048,82,\n,,83,' | sfdisk -uM  /dev/sdb'
sfdisk: unsupported unit 'M'
 *** Could not write partitions ,100,83,
,2048,82,
,,83, to device /dev/sdb
 >>> Cleaning up after install failure
runstep(): executing main for failure_cleanup
spawn(): running command 'mv /tmp/install.log /tmp/install.log.failed'
 *** Could not move /tmp/install.log to /tmp/install.log.failed
Terminated
root ~/kicktoo # 
```

``` bash
  1 part sdb 1 83 100M
  2 part sdb 2 82 2048M
  3 part sdb 3 83 +
  4 
  5 format /dev/sdb1 ext2
  6 format /dev/sdb2 swap
  7 format /dev/sdb3 ext4
  8 
  9 mountfs /dev/sdb1 ext2 /boot
 10 mountfs /dev/sdb2 swap
 11 mountfs /dev/sdb3 ext4 / noatime
 12 
 13 # retrieve latest autobuild stage version for stage_uri
 14 [ "${arch}" == "x86" ]   && stage_latest $(uname -m)
 15 [ "${arch}" == "amd64" ] && stage_latest amd64
 16 tree_type   snapshot    http://distfiles.gentoo.org/snapshots/portage-latest.tar.bz2
 17 
 18 # get kernel dotconfig from the official running kernel
 19 cat /proc/config.gz | gzip -d > /dotconfig
 20 grep -v CONFIG_EXTRA_FIRMWARE /dotconfig > /dotconfig2 ; mv /dotconfig2 /dotconfig
 21 grep -v LZO                   /dotconfig > /dotconfig2 ; mv /dotconfig2 /dotconfig
 22 kernel_config_file       /dotconfig
 23 kernel_sources           gentoo-sources
 24 initramfs_builder
 25 genkernel_kernel_opts    --loglevel=5
 26 genkernel_initramfs_opts --loglevel=5
 27 
 28 #grub2_install /dev/sdb
 29 
 30 timezone                UTC
 31 rootpw                  a
 32 #bootloader              grub
 33 keymap                  be-latin1
 34 hostname                t1700
 35 extra_packages          dhcpcd syslog-ng vim openssh
 36 
 37 #rcadd                   sshd       default
 38 #rcadd                   syslog-ng  default

```

**Comment by tsuehpsyde** [comment]
Still very much the biggest problem when trying to use kicktoo today :) 

https://bugzilla.redhat.com/show_bug.cgi?id=1183236

`livecd kicktoo # sfdisk --version
sfdisk from util-linux 2.28
livecd kicktoo # sfdisk --help | grep -A 100 Options
Options:
 -a, --append              append partitions to existing partition table
 -b, --backup              backup partition table sectors (see -O)
     --bytes               print SIZE in bytes rather than in human readable format
     --move-data[=<typescript>] move partition data after relocation (requires -N)
 -f, --force               disable all consistency checking
     --color[=<when>]      colorize output (auto, always or never)
                             colors are enabled by default
 -N, --partno <num>        specify partition number
 -n, --no-act              do everything except write to device
     --no-reread           do not check whether the device is in use
 -O, --backup-file <path>  override default backup file name
 -o, --output <list>       output columns
 -q, --quiet               suppress extra info messages
 -w, --wipe <mode>         wipe signatures (auto, always or never)
 -X, --label <name>        specify label type (dos, gpt, ...)
 -Y, --label-nested <name> specify nested label type (dos, bsd)

 -L, --Linux               deprecated, only for backward compatibility
 -u, --unit S              deprecated, only sector unit is supported

 -h, --help     display this help and exit
 -v, --version  output version information and exit

Available columns (for -o):
 gpt: Device Start End Sectors Size Type Type-UUID Attrs Name UUID
 dos: Device Start End Sectors Cylinders Size Type Id Attrs Boot End-C/H/S Start-C/H/S
 bsd: Slice Start End Sectors Cylinders Size Type Bsize Cpg Fsize
 sgi: Device Start End Sectors Cylinders Size Type Id Attrs
 sun: Device Start End Sectors Cylinders Size Type Id Flags

For more details see sfdisk(8).
livecd kicktoo #`

**Comment by r1k0** [comment]
Thank you for your feedback and sorry for the delay. As soon as I get some time will fix this.

**Comment by r1k0** [comment]
sfdisk issue fixed.
The stage_uri is broken and needs either to be rewritten or not used at all.
As I've moved away from gentoo after more than a decade of dedication (it breaks all the time) I probably won't dive into it again.
Use stage_uri in your profile and comment stage_latest calls like this:
stage_uri http://distfiles.gentoo.org/releases/amd64/autobuilds/20190131T214503Z/stage3-amd64-20190131T214503Z.tar.xz
This will work but you will then see autounmask issues which you can fix by hacking your profile using pre_*|post_* functions, take a look at other profiles and how this feature works (you can overwrite all functions in your profile this way).
If you happen to have more time than I do, I'd gladly merge your code ;o)
