### ISSUE TITLE
UEFI installation

### ISSUE THREAD

**Issue by renich** [r1k0/kicktoo#21]
I haven't figured out how to create a UEFI installation script. Part of the problem is that grub-install goes into the ESP directory; usually `/boot/efi`; and not into the MBR.

**Comment by r1k0** [comment]
Hello again,

To my knowledge, the boot type depends on the type of label set on the boot partition.
Namely, GPT or DOS types. You can choose either when using for example cfdisk.

So my advise is to manually partition (the partition is currently broken in kicktoo as sfdisk has had some changes in its options and I haven't fixed it already) and let kicktoo profile start with formatting (format call).

If you encounter more issues, do not hesitate to copy/paste outputs and the profile.

Have a good day
